FROM ghcr.io/rust-lang/rust:nightly

RUN apt-get update && apt-get install -y --no-install-recommends \
    pkg-config libgdal-dev libclang-dev curl \
    && curl -sL https://dl.min.io/client/mc/release/linux-amd64/mc -o /usr/local/bin/mc \
    && chmod +x /usr/local/bin/mc \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app
